spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: springmongotuto
      port: 27017
      host: localhost
      auto-index-creation: true
  kafka:
    bootstrap-servers: localhost:29092

kafka:
  topics:
    multiplicationSolved: multiplications-events