spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: springmongotuto
      port: 27017
      host: localhost
      auto-index-creation: true